default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  database: <%= ENV['DATABASE_NAME'] || 'ratpack' %>
  username: <%= ENV['DATABASE_USER'] || 'admin' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'testpass1' %>

development:
  <<: *default
  database: ratpack_dev

test:
  <<: *default
  database: ratpack_test

production:
  <<: *default